from os.path import join

Import('env')

# main.cpp adapts to whichever lua bindings were compiled, via the config header
# generated by modules/lua/scons.py into the build dir.
builder = env.builder()
env.AppendUnique(CPPPATH=[join(builder.build_path, "generated")])

bin = env.build_bin("src/main.cpp", name = "sihd_lua")

Return("bin")
