local root = Node.new("root", nil)
local named = Named.new("child", root)
assert(named:get_name() == "child")
assert(root:get_name() == "root")
assert(root:get_child("child") == named)
assert(named:get_parent() == root)