#ifndef __SIHD_UTIL_VERSION_HPP__
# define __SIHD_UTIL_VERSION_HPP__

# define SIHD_STR(s) #s
# define SIHD_STRINGIFY(s) SIHD_STR(s)

# define SIHD_VERSION_MAJOR {VERSION_MAJOR}
# define SIHD_VERSION_MINOR {VERSION_MINOR}
# define SIHD_VERSION_PATCH {VERSION_PATCH}

# define SIHD_VERSION_STRING SIHD_STRINGIFY(SIHD_VERSION_MAJOR) "." SIHD_STRINGIFY(SIHD_VERSION_MINOR) "." SIHD_STRINGIFY(SIHD_VERSION_PATCH)
# define SIHD_VERSION_NUM ((SIHD_VERSION_MAJOR * 100000) + (SIHD_VERSION_MINOR * 100) + (SIHD_VERSION_PATCH))

#endif