#ifndef __SIHD_UTIL_VERSION_HPP__
# define __SIHD_UTIL_VERSION_HPP__

# define SIHD_STR(s) #s
# define SIHD_STRINGIFY(s) SIHD_STR(s)

# if !defined(SIHD_VERSION_MAJOR)
#  define SIHD_VERSION_MAJOR 0
# endif

# if !defined(SIHD_VERSION_MINOR)
#  define SIHD_VERSION_MINOR 0
# endif

# if !defined(SIHD_VERSION_PATCH)
#  define SIHD_VERSION_PATCH 0
# endif

# define SIHD_VERSION_STRING SIHD_STRINGIFY(SIHD_VERSION_MAJOR) "." SIHD_STRINGIFY(SIHD_VERSION_MINOR) "." SIHD_STRINGIFY(SIHD_VERSION_PATCH)
// 2.34.76 -> 203476
# define SIHD_VERSION_NUM ((SIHD_VERSION_MAJOR * 100000) + (SIHD_VERSION_MINOR * 100) + (SIHD_VERSION_PATCH))

#endif