import os
from os.path import join, isdir

Import('env')

builder = env.builder()
conf = env.module_conf()

## Compile files by modules

src_dir = Dir("src")
test_dir = Dir("test")

modules = env.modules_to_build()

srcs = [src_dir.File("Vm.cpp"), src_dir.File("LuaGil.cpp")]
tests = [test_dir.File("main.cpp")]
bound_modules = []
for module in modules:
    if module == "lua":
        continue
    if not isdir(join(str(src_dir), module)):
        continue
    bound_modules.append(module)
    srcs += Glob(str(src_dir) + "/{}/*.cpp".format(module))
    tests += Glob(str(test_dir) + "/{}/*.cpp".format(module))

## Generated config header
#
# lua is adaptive: a binding is compiled only when its module is in the build.
# Consumers (luabin, sihd/lua.hpp) must know which ones exist, so emit a define
# per bound module. It MUST live in the build dir, not in modules/lua/include:
# the module set differs per variant (web excludes net/http) while the source
# tree is shared, so a source-tree header would go stale across builds.

generated_dir = join(builder.build_path, "generated")
config_path = join(generated_dir, "sihd", "lua", "config.hpp")

lines = [
    "#ifndef __SIHD_LUA_CONFIG_HPP__",
    "#define __SIHD_LUA_CONFIG_HPP__",
    "",
    "// Generated by modules/lua/scons.py - one define per compiled binding.",
    "",
]
lines += ["#define SIHD_LUA_WITH_{} 1".format(m.upper()) for m in sorted(bound_modules)]
lines += ["", "#endif", ""]
content = "\n".join(lines)

def _write_lua_config(target, source, env):
    os.makedirs(os.path.dirname(str(target[0])), exist_ok=True)
    with open(str(target[0]), "w") as f:
        f.write(source[0].get_text_contents())

config_node = env.Command(
    config_path,
    env.Value(content),
    env.Action(_write_lua_config, "Generating $TARGET"),
)

env.AppendUnique(CPPPATH=[generated_dir])
# also ship it alongside the installed headers
env.Install(join(builder.build_hdr_path, "sihd", "lua"), config_node)

lib = env.build_lib(srcs)
test = env.build_test(tests, libs = [env.module_format_name()])

Return('lib')
